# Generated by Django 2.1.5 on 2019-01-16 02:30

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
