# Generated by Django 2.1.5 on 2019-01-17 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0004_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_id', models.IntegerField()),
                ('goods_name', models.CharField(max_length=32)),
                ('goods_price', models.FloatField()),
                ('goods_num', models.IntegerField()),
                ('goods_picture', models.ImageField(upload_to='images')),
                ('order', models.ForeignKey(on_delete=True, to='Buyer.Order')),
            ],
        ),
    ]
